//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAsada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Inventario
    {
        public int ID { get; set; }
        public Nullable<int> ID_compra { get; set; }
        public Nullable<int> ID_inventario { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Registro_Compra Registro_Compra { get; set; }
        public virtual Inventario_Stock Inventario_Stock { get; set; }
    }
}
