//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAsada.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asadaEntities : DbContext
    {
        public asadaEntities()
            : base("name=asadaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aforo> Aforo { get; set; }
        public virtual DbSet<Agua_No_Contabilizada> Agua_No_Contabilizada { get; set; }
        public virtual DbSet<Asada_Quejas> Asada_Quejas { get; set; }
        public virtual DbSet<Averias> Averias { get; set; }
        public virtual DbSet<Cheques> Cheques { get; set; }
        public virtual DbSet<Cloracion> Cloracion { get; set; }
        public virtual DbSet<Compra_Inventario> Compra_Inventario { get; set; }
        public virtual DbSet<Cuentas_Bancarias> Cuentas_Bancarias { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Factura_Cheque> Factura_Cheque { get; set; }
        public virtual DbSet<Inventario_averia> Inventario_averia { get; set; }
        public virtual DbSet<Inventario_Stock> Inventario_Stock { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Prestamos_Inventario> Prestamos_Inventario { get; set; }
        public virtual DbSet<Reciclaje> Reciclaje { get; set; }
        public virtual DbSet<Registro_Compra> Registro_Compra { get; set; }
        public virtual DbSet<Registro_Salidas> Registro_Salidas { get; set; }
        public virtual DbSet<Salidas_Inventario> Salidas_Inventario { get; set; }
    }
}
